'use strict';var pea={TAB:0,ol:1,wp:2},Cv=function(){return new rb("MediaRouter.CastStreaming.Session.Launch")},Dv=function(){return new xb("MediaRouter.CastStreaming.Session.Length")},Ev=function(a){Bb("MediaRouter.CastStreaming.Start.Success",a,pea)};var Fv=fb("mr.mirror.cast.LogUploader"),Hv=function(a,b,c){Gv("raw_events.log.gz",a,b,c);return b?"https://crash.corp.google.com/samples?reportid=&q="+encodeURIComponent("UserComments='"+b+"'"):""},Gv=function(a,b,c,d){if(0==b.size)Fv.info("Trying to upload an empty file to Crash"),d&&d(null);else{var e=new FormData;e.append("prod","Cast");e.append("ver",chrome.runtime.getManifest().version);e.append(a,b);c&&e.append("comments",c);ku("https://clients2.google.com/cr/report",function(f){f=f.target;
var g=null;su(f)?(g=tu(f),Fv.info("Upload to Crash succeeded: "+g)):Fv.info("Upload to Crash failed. HTTP status: "+f.Xa());d&&d(g)},"POST",e,void 0,3E4)}};var Iv=function(){this.g=0;km(this)},Kv=function(){Jv||(Jv=new Iv);return Jv},qea=function(){var a=Kv(),b={fraction:.01,autoSubmitTimeLimitMillis:6048E5},c=b.autoSubmitTimeLimitMillis,d=Date.now();return a.g&&c&&d-a.g<c?!1:Math.random()<b.fraction};Iv.prototype.Ia=function(){return"mirror.cast.LogUtils"};Iv.prototype.sb=function(){return[void 0,{lastAutoSubmitMillis:this.g}]};Iv.prototype.qb=function(){var a=im(this);this.g=a&&a.lastAutoSubmitMillis||0};var Jv=null;fb("mr.mirror.cast.LogUtils");var Lv={Nz:"OFFER",vv:"ANSWER",qA:"PRESENTATION",qx:"GET_STATUS",DB:"STATUS_RESPONSE",px:"GET_CAPABILITIES",Uv:"CAPABILITIES_RESPONSE",eB:"RPC"};var rea=function(){this.capabilities=this.status=this.g=this.error=this.rpc=this.result=this.type=this.h=this.sessionId=null},tea=function(a){try{if("string"!==typeof a)throw SyntaxError("Cannot parse non-string as JSON");var b;Mv(JSON.parse(a),function(d){b=sea(d)},function(){throw Error("non-Object result from JSON parse");});return b}catch(d){var c=d instanceof SyntaxError?"JSON parse error: "+d.message:"Type coercion error: "+d.message}"string"==typeof a?a="a string: "+a:a instanceof ArrayBuffer?
(a=new Uint8Array(a),a="an ArrayBuffer whose base64 is "+btoa(String.fromCharCode.apply(null,a))):a="of invalid data type "+typeof a;throw Error(c+". Input was "+a);},sea=function(a){var b=new rea;null!=a.sessionId&&(b.sessionId=String(a.sessionId));Nv(a.seqNum,function(f){b.h=f},function(){throw Error('"seqNum" must be a number');});if("type"in a){for(var c=String(a.type).toUpperCase(),d=l(Object.keys(Lv)),e=d.next();!e.done;e=d.next())if(Lv[e.value]==c){b.type=c;break}if(!b.type)throw Error('not a known message "type"');
}"result"in a&&(b.result=String(a.result));if("rpc"in a){if("string"!==typeof a.rpc)throw Error('"rpc" must be a String containing a base64 payload');b.rpc=new Uint8Array([].concat(n(atob(a.rpc))).map(function(f){return f.charCodeAt(0)}))}Mv(a.error,function(f){b.error=uea(f)},function(){throw Error('"error" must be an Object');});Mv(a.answer,function(f){b.g=vea(f)},function(){throw Error('"answer" must be an Object');});Mv(a.status,function(f){b.status=wea(f)},function(){throw Error('"status" must be an Object');
});Mv(a.capabilities,function(f){b.capabilities=xea(f)},function(){throw Error('"capabilities" must be an Object');});return b},Mv=function(a,b,c){void 0!==a&&(a instanceof Object?b(a):c())},Nv=function(a,b,c){void 0!==a&&("number"!==typeof a?c():b(a))},Ov=function(a,b,c){void 0!==a&&(a instanceof Array&&a.every(function(d){return"number"===typeof d})?b(a):c())},Pv=function(a,b,c){void 0!==a&&(a instanceof Array?b(a.map(function(d){return String(d)})):c())},yea=function(){this.w=null;this.g=[];this.h=
[];this.j=this.l=this.m=null},vea=function(a){var b=new yea;Nv(a.udpPort,function(c){b.w=c},function(){throw Error('"answer.udpPort" must be a number');});Ov(a.sendIndexes,function(c){b.g=c},function(){throw Error('"answer.sendIndexes" must be an array of numbers');});Ov(a.ssrcs,function(c){b.h=c},function(){throw Error('"answer.ssrcs" must be an array of numbers');});"IV"in a&&(b.m=String(a.IV));"receiverGetStatus"in a&&(b.l="true"==String(a.receiverGetStatus).toLowerCase());"castMode"in a&&(b.j=
String(a.castMode));return b},zea=function(){this.details=this.description=this.code=null},uea=function(a){var b=new zea;Nv(a.code,function(c){b.code=c},function(){throw Error('"error.code" must be a number');});"description"in a&&(b.description=String(a.description));Mv(a.details,function(c){b.details=c},function(){throw Error('"error.details" must be an Object');});return b},Aea=function(){this.h=this.g=null},wea=function(a){var b=new Aea;Nv(a.wifiSnr,function(c){b.g=c},function(){throw Error('"status.wifiSnr" must be a number');
});Ov(a.wifiSpeed,function(c){b.h=c},function(){throw Error('"status.wifiSpeed" must be an array of numbers');});return b},Bea=function(){this.h=this.g=null},xea=function(a){var b=new Bea;Pv(a.mediaCaps,function(c){b.g=c},function(){throw Error('"capabilities.mediaCaps" must be an array');});if("keySystems"in a){a=a.keySystems;if(!(a instanceof Array))throw Error('"capabilities.keySystems" must be an array');b.h=a.map(function(c){var d;Mv(c,function(e){d=Cea(e)},function(){throw Error('"capabilities.keySystems" entries must be *Objects');
});return d})}return b},Dea=function(){this.j=this.s=this.m=this.w=this.D=this.g=this.u=this.h=this.initDataTypes=this.l=null},Cea=function(a){var b=new Dea;"keySystemName"in a&&(b.l=String(a.keySystemName));Pv(a.initDataTypes,function(c){b.initDataTypes=c},function(){throw Error('"capabilities.initDataTypes" must be an array');});Pv(a.codecs,function(c){b.h=c},function(){throw Error('"capabilities.codecs" must be an array');});Pv(a.secureCodecs,function(c){b.u=c},function(){throw Error('"capabilities.secureCodecs" must be an array');
});Pv(a.audioRobustness,function(c){b.g=c},function(){throw Error('"capabilities.audioRobustness" must be an array');});Pv(a.videoRobustness,function(c){b.D=c},function(){throw Error('"capabilities.videoRobustness" must be an array');});"persistentLicenseSessionSupport"in a&&(b.w=String(a.persistentLicenseSessionSupport));"persistentReleaseMessageSessionSupport"in a&&(b.m=String(a.persistentReleaseMessageSessionSupport));"persistentStateSupport"in a&&(b.s=String(a.persistentStateSupport));"distinctiveIdentifierSupport"in
a&&(b.j=String(a.distinctiveIdentifierSupport));return b};var Qv=function(a){this.o=fb("mr.mirror.cast.MessageDispatcher");this.l=a;this.g=null;this.h=new Map;this.j=0};Qv.prototype.subscribe=function(a,b){if(this.h.has(a))throw Error("Attempt to multiple-subscribe to the same response type: "+a);this.h.set(a,b);this.j=0;nb(this.o,"Added subscriber for "+a+"-type messages.");this.g||(this.g=Vu(this.l),this.g.onMessage=this.w.bind(this))};
var Rv=function(a,b){a.h.delete(b)&&nb(a.o,function(){return"Removed subscriber of "+b+"-type messages."});0==a.h.size&&a.g&&(a.g.eb(),a.g=null)};Qv.prototype.sendMessage=function(a){return this.g?"RPC"==a.type?this.g.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.remoting"}):this.g.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.webrtc"}):Promise.reject(Error("Require at least one subscriber before sending messages."))};
var Sv=function(a,b,c,d,e){var f=null,g=function(){Rv(a,c);null!=f&&(clearTimeout(f),f=null)};try{a.subscribe(c,function(k){e(k)&&g()})}catch(k){e(null,k);return}f=setTimeout(function(){g();e(null,Error("timeout"))},d);a.sendMessage(b).catch(function(k){g();e(null,k)})};
Qv.prototype.w=function(a){if(a&&"string"===typeof a.namespace_&&a.namespace_.startsWith("urn:x-cast:com.google.cast.")){do{var b=void 0;try{b=tea(a.data)}catch(d){b=d.message;break}if(b.type){var c=this.h.get(b.type);if(c)try{c(b);return}catch(d){b="Error thrown during delivery. Response was: "+(JSON.stringify(b)+". Error from subscriber callback was: ")+(d.message+".")}else b="Message was ignored: "+JSON.stringify(b)}else b="Message did not include response type: "+JSON.stringify(b)}while(0);10>
this.j?this.o.K(b):nb(this.o,b);++this.j}};var Tv=function(){this.g=Promise.resolve(1)},Vv=function(a,b,c){return Uv(a,function(d){return d==b},c)},Eea=function(a,b){var c=[3,4];return Uv(a,function(d){return-1!=c.indexOf(d)},b)},Wv=function(a,b){a.g=a.g.catch(function(){return 1});return Uv(a,function(){return!0},b)},Uv=function(a,b,c){var d,e,f=new Promise(function(g,k){d=g;e=k});a.g=a.g.then(function(g){if(!b(g))return e(Error("Operation requires a different starting checkpoint than "+g)),Promise.resolve(g);var k=new Fea(g);try{var m=c(k)}catch(p){m=
Promise.reject(p)}return m.then(function(p){return d(p)},function(p){return e(p)}).then(function(){if(null===k.g)throw Error("A prior operation that started at "+(g+" did not complete."));return k.g})},function(g){e(g);throw g;});return f},Fea=function(a){this.h=a;this.g=null},Xv=function(a,b){a.g="number"===typeof b?b:a.h};var Yv=chrome.cast.streaming,$v=function(a,b,c,d,e){this.L=a.sessionId;this.D=a.sg;this.N=a.ve;this.j=b;this.J=c;this.M=d;this.W=Zv(e,"onAnswer",this.D);this.X=Zv(e,"onSessionStop",this.D);this.o=fb("mr.mirror.cast.StreamingLaunchWorkflow");this.G=new Tv;this.s=this.F=this.u=this.h=this.g=this.m=this.w=this.l=null};
$v.prototype.start=function(a,b,c){var d=this;if(!a&&!b)return Promise.reject(Error("No tracks to stream"));var e=a instanceof aw,f=b instanceof aw;(e&&b&&!f||f&&a&&!e)&&Gb("Mixing remoting and non-remoting tracks");return Vv(this.G,1,function(g){d.l=a;d.w=b;d.m=c;d.o.info(function(){return"Launching streaming for "+bw(d)+" to a "+(d.N+".")});return Gea(d).then(d.H.bind(d)).then(function(k){return Hea(d,k).then(function(m){d.W();var p=Iea(d,m,k);d.g=cw(d,d.g,p);d.h=cw(d,d.h,p);if(!d.g&&!d.h)throw Error("Receiver did not select any offers from: "+
JSON.stringify(k));d.F=!!m.l;d.s=function(u,A){u==d.g?d.m.tf("Audio stream (id="+u+") error: "+A):u==d.h&&d.m.tf("Video stream (id="+u+") error: "+A)};Yv.rtpStream.onError.addListener(d.s);return Jea(d,m,p)})}).then(function(){d.o.info(function(){return"Launched streaming for "+bw(d)});d.m.Kg(d);Xv(g,2);return{Lq:d.g,dv:d.h}})})};
$v.prototype.stop=function(){var a=this;return Wv(this.G,function(b){if(!a.l&&!a.w)return Xv(b,1),Promise.resolve();a.o.info(function(){return"Stopping streaming for "+bw(a)+"."});a.s&&(Yv.rtpStream.onError.removeListener(a.s),a.s=null);if(a.m){var c=a.m.xh();a.m=null}else c=Promise.resolve();return c.then(function(){a.g&&(Yv.rtpStream.stop(a.g),Yv.rtpStream.destroy(a.g),a.g=null);a.h&&(Yv.rtpStream.stop(a.h),Yv.rtpStream.destroy(a.h),a.h=null);a.u&&(Yv.udpTransport.destroy(a.u),a.u=null);a.X();a.o.info(function(){return"Stopped streaming for "+
bw(a)+"."});a.l=null;a.w=null;Xv(b,1)})})};
var Kea=function(a,b){var c=JSON.stringify(b);return Promise.all([a.g&&new Promise(function(d){return Yv.rtpStream.getRawEvents(a.g,c,d)}),a.h&&new Promise(function(d){return Yv.rtpStream.getRawEvents(a.h,c,d)})]).catch(function(d){a.o.error("Unexpected error when calling getRawEvents()",d);return[]}).then(function(d){return new Blob(d.filter(function(e){return!!e}),{type:"application/gzip"})})},Lea=function(a){return Promise.all([a.g&&new Promise(function(b){return Yv.rtpStream.getStats(a.g,b)}),
a.h&&new Promise(function(b){return Yv.rtpStream.getStats(a.h,b)})]).catch(function(b){a.o.error("Unexpected error when calling getStats()",b);return[]}).then(function(b){return Object.assign.apply(Object,[{}].concat(n(b.filter(function(c){return!!c}))))})},bw=function(a){if(a.l&&a.w)var b="audio+video ";else if(a.l)b="audio-only ";else if(a.w)b="video-only ";else return"stopped";return a.l instanceof aw||a.w instanceof aw?b+"remoting":b+"streaming"},Gea=function(a){return new Promise(function(b){var c=
function(d,e,f){d&&!a.l&&(Yv.rtpStream.destroy(d),d=null);e&&!a.w&&(Yv.rtpStream.destroy(e),e=null);a.o.info(function(){return"Created Cast Streaming session: audioStreamId="+d+", videoStreamId="+e+"."});a.g=d;a.h=e;a.u=f;b()};a.l instanceof aw||a.w instanceof aw?Yv.session.create(null,null,c):Yv.session.create(a.l,a.w,c)})};
$v.prototype.H=function(){for(var a=Wj(),b=Wj(),c=[],d=l([this.g,this.h]),e=d.next();!e.done;e=d.next())if(e=e.value)for(var f=e==this.g,g=f?127:96,k=f?Math.floor(499999*Math.random())+1:Math.floor(499999*Math.random())+500001,m=f?48E3:9E4,p=l(Yv.rtpStream.getSupportedParams(e)),u=p.next();!u.done;u=p.next())u=u.value,u.payload.payloadType=g,u.payload.maxLatency=this.j.maxLatencyMillis,u.payload.minLatency=this.j.minLatencyMillis,u.payload.animatedLatency=this.j.animatedLatencyMillis,u.payload.ssrc=
k,u.payload.clockRate=m,u.payload.aesKey=a,u.payload.aesIvMask=b,f?(u.payload.channels=2,u.payload.maxBitrate=this.j.audioBitrate,u.payload.maxFrameRate=100):(u.payload.minBitrate=this.j.minVideoBitrate,u.payload.maxBitrate=this.j.maxVideoBitrate,u.payload.maxFrameRate=this.j.maxFrameRate),c.push(new Mea(e,u));return c};
var cw=function(a,b,c){b&&!c.some(function(d){return d.vg==b})&&(a.o.K("Destroying RTP stream not selected by the receiver: id="+b),Yv.rtpStream.destroy(b),b=null);return b},Hea=function(a,b){return new Promise(function(c,d){for(var e=[],f=0;f<b.length;++f){var g=b[f].params,k={index:f,codecName:g.payload.codecName.toLowerCase(),rtpProfile:"cast",rtpPayloadType:g.payload.payloadType,ssrc:g.payload.ssrc,targetDelay:g.payload.animatedLatency,aesKey:g.payload.aesKey,aesIvMask:g.payload.aesIvMask,timeBase:"1/"+
g.payload.clockRate,receiverRtcpEventLog:a.j.enableLogging,rtpExtensions:["adaptive_playout_delay"]};a.j.dscpEnabled&&(k.receiverRtcpDscp=46);127==g.payload.payloadType?Object.assign(k,{type:"audio_source",bitRate:0<g.payload.maxBitrate?1E3*g.payload.maxBitrate:60*g.payload.maxFrameRate+g.payload.clockRate*g.payload.channels,sampleRate:g.payload.clockRate,channels:g.payload.channels}):Object.assign(k,{type:"video_source",renderMode:"video",maxFrameRate:Math.round(1E3*g.payload.maxFrameRate)+"/1000",
maxBitRate:1E3*g.payload.maxBitrate,resolutions:[{width:a.j.maxWidth,height:a.j.maxHeight}]});e.push(k)}var m=a.l instanceof aw||a.w instanceof aw?"remoting":"mirroring",p={type:"OFFER",sessionId:a.L,seqNum:zn(a.J),offer:{castMode:m,receiverGetStatus:!0,supportedStreams:e}};a.o.info(function(){return"Sending OFFER message: "+JSON.stringify(p)});Sv(a.M,p,"ANSWER",1E4,function(u,A){if(null==u)d(A);else if("ok"==u.result&&u.g){if(u.h!=p.seqNum)return a.o.K("Ignoring ANSWER for OFFER with different seqNum: "+
JSON.stringify(u)),!1;((A=u.g.j)&&A!=m||!A&&"mirroring"!=m)&&a.o.error("Expected receiver to ANSWER with castMode="+m+", but got: "+A);nb(a.o,function(){return"Received ANSWER: "+JSON.stringify(u)});c(u.g)}else d(Error("Non-OK ANSWER received: "+JSON.stringify(u)));return!0})})},Iea=function(a,b,c){if(b.g.length!=b.h.length)return a.o.error("sendIndexes.length != ssrcs.length in ANSWER: "+JSON.stringify(b)),[];for(var d=[],e={},f=0;f<b.g.length;e={Cf:e.Cf},++f){var g=b.g[f];if(0>g||g>=c.length)return a.o.error("Receiver selected invalid index ("+
g+" < "+c.length+") in ANSWER: "+JSON.stringify(b)),[];e.Cf=c[g];if(d.some(function(k){return function(m){return m.vg==k.Cf.vg}}(e)))return a.o.error("Receiver selected same RTP stream twice in ANSWER: "+JSON.stringify(b)),[];e.Cf.params.payload.feedbackSsrc=b.h[g];if(d.some(function(k){return function(m){return m.params.payload.feedbackSsrc==k.Cf.params.payload.feedbackSsrc}}(e)))return a.o.error("Receiver provided same SSRC for two different RTP streams in ANSWER: "+JSON.stringify(b)),[];d.push(e.Cf)}return d},
Jea=function(a,b,c){var d=null,e=function(){d&&(Yv.rtpStream.onStarted.removeListener(d),d=null)};return(new Promise(function(f,g){var k=b.w||2344;a.o.info(function(){return"Starting RTP streams to receiver at "+(a.D+":"+k)+(" for selected offers: "+JSON.stringify(c))});var m=a.u||-1;a.j.dscpEnabled&&(a.o.info("Enabled DSCP in sender."),Yv.udpTransport.setOptions(m,{DSCP:!0}));Yv.udpTransport.setDestination(m,{address:a.D,port:k});var p=new Set(c.map(function(A){return A.vg}));d=function(A){p.delete(A);
0==p.size&&f()};Yv.rtpStream.onStarted.addListener(d);m=l(c);for(var u=m.next();!u.done;u=m.next())u=u.value,Yv.rtpStream.toggleLogging(u.vg,a.j.enableLogging),Yv.rtpStream.start(u.vg,u.params);setTimeout(function(){g(Error("Timeout: RTP streams failed to start."))},1E4)})).then(e).catch(function(f){e();throw f;})},Zv=function(a,b,c){var d=this;return a&&b in a?function(){try{a[b](c)}catch(e){d.o.error("Error from testHooks."+b,e)}}:function(){}},Mea=function(a,b){this.vg=a;this.params=b},aw=function(){};var dw=function(a,b,c,d,e,f){this.s=a;this.M=Nea(b,this.s.yb);this.J=new $v(this.s.yb,c,d,e,f);this.F=e;this.w=new Tv;this.j=new Oea;this.G=new mojo.Binding(mojo.MirrorServiceRemoter,this,null);this.o=fb("mr.mirror.cast.MediaRemoter");this.D=this.g=this.m=this.l=this.H=null;this.h=!0;this.u=this.L.bind(this)};
dw.prototype.initialize=function(a,b){var c=this;return Vv(this.w,1,function(d){c.H=a;c.l=b;var e=c.G.createInterfacePtrAndBind();c.G.setConnectionErrorHandler(function(){c.o.info("Remoter mojo pipe connection error.");ew(c)});c.g=new mojo.MirrorServiceRemotingSourcePtr;var f=oj(c.s.mediaSource||"");if(!f)throw Error("Failed to parse tab ID from source:\n          "+c.s.mediaSource);c.o.info("Connecting remoter to browser: tabId="+f);(Xi.get("mr.ProviderManager")||null).onMediaRemoterCreated(f,e,
mojo.makeRequest(c.g));c.g.ptr.setConnectionErrorHandler(function(){c.o.info("RemotingSource mojo pipe connection error.");ew(c)});return Pea(c).then(function(){if(c.h)c.g.onSinkAvailable(c.M);Xv(d,2)})})};
var ew=function(a){return Wv(a.w,function(b){a.g&&(a.g.ptr.reset(),a.g=null);var c=a.m;a.m=null;a.l=null;a.H=null;a.G.close();chrome.settingsPrivate.onPrefsChanged.hasListener(a.u)&&chrome.settingsPrivate.onPrefsChanged.removeListener(a.u);return new Promise(function(d){window.setTimeout(function(){fw(a).then(function(){Xv(b,1);d();c&&c()})},250)})})};h=dw.prototype;h.ru=function(a){gw(this.j,a)};h.Kg=function(a){this.l&&this.l.Kg(a)};h.xh=function(){return this.l?this.l.xh():Promise.resolve()};
h.tf=function(a,b){this.o.error("Error during streaming: "+a,b);if(this.g)this.g.onError();ew(this)};
h.start=function(){var a=this,b=!1;this.o.info(function(){b=!0;return"Starting next media remoting session."});b&&Qea(this.j,function(c){return a.o.info(c)});Rea(this.j);Vv(this.w,2,function(c){return(0,a.H)().then(function(d){a.m=d;a.F.subscribe("RPC",function(e){if(e.rpc){var f=a.j;e=e.rpc;f.m&&(++f.s,f.h+=e.length,f.m(e))}});Xv(c,3)}).catch(function(d){return fw(a).then(function(){Xv(c);throw d;})})}).then(function(){a.o.info("Remoting started successfully.")}).catch(function(c){a.o.error("Failed to start remoting",
c);a.g.onError()})};h.Qu=function(a,b){var c=this;return Vv(this.w,3,function(d){return c.J.start(a?new aw:null,b?new aw:null,c).then(function(e){Sea(c.j,function(f){return c.F.sendMessage(f)},function(f){c.g.onMessageFromSink(f)});Xv(d,4);return{audio_stream_id:e.Lq||-1,video_stream_id:e.dv||-1}}).catch(function(e){return fw(c).then(function(){Xv(d);throw e;})})}).catch(function(d){c.o.error("Failed to start remoting streams",d);ew(c);return{audio_stream_id:-1,video_stream_id:-1}})};
h.stop=function(a){var b=this;Eea(this.w,function(c){b.g.onStopped(a);return fw(b).then(function(){b.o.info("Remoting stopped.");Xv(c,5);(0,b.m)().then(function(){return Vv(b.w,5,function(d){if(b.g&&b.h)b.g.onSinkAvailable(b.M);Xv(d,2);return Promise.resolve()})}).catch(function(d){throw d;});b.m=null})}).catch(function(c){b.o.error("Failed to stop remoting: ",c);ew(b)})};
h.kr=function(){null===this.D&&(this.D=sf(this.s.yb.sg).then(function(a){return a.h||!1}));return this.D.then(function(a){return{rate:(a?1E7:5E6)/8}})};
var fw=function(a){return a.J.stop().then(function(){Rv(a.F,"RPC");Tea(a.j);hw(a.j)})},Pea=function(a){return new Promise(function(b){chrome.settingsPrivate.getPref("media_router.media_remoting.enabled",function(c){chrome.runtime.lastError?a.o.error("Encountered error getting media remoting pref: "+JSON.stringify(chrome.runtime.lastError)):c.type!=chrome.settingsPrivate.PrefType.BOOLEAN?a.o.error("Pref value not a boolean: "+JSON.stringify(c)):(a.h=!!c.value,a.o.info("Initializing mediaRemotingEnabled_ with value read from pref: "+
a.h));chrome.settingsPrivate.onPrefsChanged.hasListener(a.u)||chrome.settingsPrivate.onPrefsChanged.addListener(a.u);b()})})};
dw.prototype.L=function(a){if(this.g){a=l(a);for(var b=a.next();!b.done;b=a.next())if(b=b.value,"media_router.media_remoting.enabled"==b.key){if(b.type!=chrome.settingsPrivate.PrefType.BOOLEAN){this.o.error("Pref value not a boolean: "+JSON.stringify(b));break}a=!!b.value;if(this.h==a)break;this.h=a;this.o.info("mediaRemotingEnabled_ changed to: "+this.h);if(this.h)this.g.onSinkAvailable(this.M);else this.g.onStopped(mojo.RemotingStopReason.USER_DISABLED);break}}};
var Nea=function(a,b){var c=this,d=new mojo.RemotingSinkMetadata;d.features=[];d.friendly_name=b.Mu||"";d.audio_capabilities=[];d.video_capabilities=[];var e=mojo.RemotingSinkAudioCapability,f=mojo.RemotingSinkVideoCapability,g=d.audio_capabilities,k=d.video_capabilities,m=b.ve||"";(a.g||[]).forEach(function(p){switch(p){case "audio":g.push(e.CODEC_BASELINE_SET);break;case "aac":g.push(e.CODEC_AAC);break;case "opus":g.push(e.CODEC_OPUS);break;case "video":k.push(f.CODEC_BASELINE_SET);break;case "4k":k.push(f.SUPPORT_4K);
break;case "h264":k.push(f.CODEC_H264);break;case "vp8":k.push(f.CODEC_VP8);break;case "vp9":m.startsWith("Chromecast Ultra")&&k.push(f.CODEC_VP9);break;case "hevc":m.startsWith("Chromecast Ultra")&&k.push(f.CODEC_HEVC);break;default:c.o.info("Unknown mediaCap name: "+p)}});b.ve&&"Chromecast Ultra"==b.ve&&k.push(f.SUPPORT_4K);return d};dw.prototype.estimateTransmissionCapacity=dw.prototype.kr;dw.prototype.stop=dw.prototype.stop;dw.prototype.startDataStreams=dw.prototype.Qu;dw.prototype.start=dw.prototype.start;
dw.prototype.sendMessageToSink=dw.prototype.ru;
var Oea=function(){this.m=this.w=this.g=null;this.D=this.h=this.s=this.j=this.u=0;this.l=null},Rea=function(a){a.g=[];iw(a,performance.now())},Sea=function(a,b,c){a.w=b;a.m=c;a.g?(b=a.g,a.g=null,b.forEach(function(d){return gw(a,d.data).then(d.tu,d.fo)})):iw(a,performance.now())},Tea=function(a){if(a.g){var b=Error("Stop before delivering pending message");a.g.forEach(function(c){return c.fo(b)});a.g=null}a.w=null;a.m=null},gw=function(a,b){if(a.w){var c=btoa(String.fromCharCode.apply(null,b));++a.u;
a.j+=b.length;return a.w({type:"RPC",rpc:c})}return a.g?new Promise(function(d,e){a.g.push({data:b,tu:d,fo:e})}):Promise.reject(Error("RPC pipe not started"))},Qea=function(a,b){hw(a);a.l=setInterval(function(){if(a.g)var c=a.g.length+" messages are waiting to send.";else{c=performance.now();var d=(c-a.D)/1E3;d="Over the past "+d.toFixed(1)+" seconds, sent "+(a.u+" messages ("+Math.round(a.j/d)+" bytes/sec) and received ")+(a.s+" messages ("+Math.round(a.h/d)+" bytes/sec).");iw(a,c);c=d}b(c)},3E4)},
hw=function(a){null!=a.l&&(clearInterval(a.l),a.l=null)},iw=function(a,b){a.u=0;a.j=0;a.s=0;a.h=0;a.D=b};var Uea=function(a){return a&&a.getAudioTracks()&&0<a.getAudioTracks().length?a.getAudioTracks()[0]:null},Vea=function(a){return a&&a.getVideoTracks()&&0<a.getVideoTracks().length?a.getVideoTracks()[0]:null};var jw=function(a,b,c,d,e){this.j=new $v(a,b,c,d,void 0===e?null:e);this.o=fb("mr.mirror.cast.MediaStreamer");this.w=new Tv;this.l=this.h=this.g=this.m=null};jw.prototype.start=function(a,b){var c=this;return Vv(this.w,1,function(d){c.m=a;c.g=Uea(a);c.g&&"ended"==c.g.readyState&&(c.g=null);c.h=Vea(a);c.h&&"ended"==c.h.readyState&&(c.h=null);if(!c.g&&!c.h)return Xv(d),Promise.reject(Error("No MediaStream tracks to stream."));c.l=b;return c.j.start(c.g,c.h,c.l).then(function(){return Xv(d,2)})})};
jw.prototype.stop=function(){var a=this;return Wv(this.w,function(b){return a.j.stop().then(function(){a.g=null;a.h=null;a.m=null;a.l=null;Xv(b,1)})})};var Wea=function(a){return Vv(a.w,2,function(b){a.o.info("Suspending media streaming...");return a.j.stop().then(function(){a.o.info("Suspended media streaming.");Xv(b,3)})})};
jw.prototype.resume=function(){var a=this;return Vv(this.w,3,function(b){a.g&&"ended"==a.g.readyState&&(a.g=null);a.h&&"ended"==a.h.readyState&&(a.h=null);if(!a.g&&!a.h)return Promise.reject(Error("Cannot resume: All tracks have ended."));a.o.info("Resuming media streaming...");return a.j.start(a.g,a.h,a.l).then(function(){a.o.info("Resumed media streaming.");Xv(b,2)})})};var kw=function(a,b,c){this.w=a;this.l=b;this.j=c;this.o=fb("mr.mirror.cast.WifiStatusMonitor");this.g=null;this.h=[]};kw.prototype.start=function(){var a=this;null==this.g&&(nb(this.o,"Starting Wifi Status Monitoring."),this.h=[],this.j.subscribe("STATUS_RESPONSE",function(b){return Xea(a,b)}),this.g=setInterval(function(){return lw(a)},12E4),lw(this))};kw.prototype.stop=function(){null!=this.g&&(nb(this.o,"Stopping Wifi Status Monitoring."),clearInterval(this.g),this.g=null,Rv(this.j,"STATUS_RESPONSE"))};
var Xea=function(a,b){if(null!=a.g)if(b.status){var c={};null!=b.status.g&&(c.wifiSnr=b.status.g);null!=b.status.h&&(c.wifiSpeed=b.status.h[3]);0==Object.keys(c).length?a.o.K(function(){return"No status fields populated in response: "+JSON.stringify(b)}):(c.timestamp=Date.now(),30==a.h.length&&a.h.shift(),a.h.push(c),a.o.info(function(){return"Current Wifi status: "+JSON.stringify(c)}))}else a.o.K(function(){return"Ignoring response without status: "+JSON.stringify(b)})},lw=function(a){a.j.sendMessage({type:"GET_STATUS",
sessionId:a.w,seqNum:zn(a.l),get_status:["wifiSnr","wifiSpeed"]})};var mw=function(a,b,c,d){this.M=b.sg;this.s={extVersion:chrome.runtime.getManifest().version,extChannel:"public",mirrorSettings:Dj(a),sender:navigator.userAgent||"UNKNOWN",receiverProductName:b.ve};this.H=c;this.F=d;this.l=this.h=this.u=this.m=this.w=this.D=this.j=null;this.g=[]};mw.prototype.Kg=function(a){null!=this.h&&clearInterval(this.h);this.j=a;this.D=Date.now();this.h=setInterval(this.G.bind(this,a),9E5)};
mw.prototype.xh=function(){null!=this.h&&(clearInterval(this.h),this.h=null);if(null!=this.j){var a=this.G(this.j);this.j=null;return a}return Promise.resolve()};mw.prototype.tf=function(a,b){null==this.w&&(this.w=Date.now(),"function"===typeof a?this.m=a():"string"===typeof a&&(this.m=a),b&&"string"===typeof b.stack&&(this.u=b.stack))};
var Yea=function(a,b){return(null==a.j?Promise.resolve():a.G(a.j)).then(function(){var c=b.map(function(d){d=nw(a,d);var e=d.map(function(g){return g.events}).filter(function(g){return null!=g}),f=["["];d.map(function(g){return g.ug}).forEach(function(g,k){0<k&&f.push(",");f.push(g)});f.push("]");return{events:new Blob(e,{type:"application/gzip"}),ug:new Blob(f,{type:"application/json"})}});a.g=[];return c})};
mw.prototype.G=function(a){var b=this;if(null!=this.l)return this.l;var c=sf(this.M).then(function(d){d={receiverVersion:d.g,receiverConnected:d.l,receiverOnEthernet:d.h,receiverHasUpdatePending:d.j,receiverUptimeSeconds:d.w};Object.assign(d,b.s);var e=Date.now();Object.assign(d,{startTime:b.D,endTime:e,activity:bw(a),receiverWifiStatus:Array.from(b.F.h)});b.D=e;null!=b.w&&(Object.assign(d,{streamingErrorTime:b.w,streamingErrorMessage:b.m,streamingErrorCause:b.u}),b.w=null,b.m=null,b.u=null);return d});
return(this.l=Promise.all([c.then(function(d){return Kea(a,d)}),c,Lea(a)]).then(function(d){var e=l(d);d=e.next().value;var f=e.next().value;e=e.next().value;b.g.push({events:d,ug:new Blob([JSON.stringify(Object.assign({tags:f},e))],{type:"application/json"})});b.g=nw(b,b.H);b.l=null}))||Promise.resolve()};
var nw=function(a,b){b-=2;for(var c=[],d=a.g.length-1;0<=d;--d){b-=a.g[d].ug.size+1;if(0>b)break;c.push({events:null,ug:a.g[d].ug});if(null!=a.g[d].events){var e=a.g[d].events.size;b>=e&&(c[c.length-1].events=a.g[d].events,b-=e)}}return c.reverse()};var ow=fb("mr.NetworkUtils"),pw=function(a,b){if(!Hi)return Promise.reject("TDLS feature not enabled.");ow.info("setTDLSState_: ip="+a+", state="+b);return new Promise(function(c,d){chrome.networkingPrivate.setWifiTDLSEnabledState(a,b,function(e){chrome.runtime.lastError?(ow.K("Unable to set TDLS state: state = "+b+", error = "+chrome.runtime.lastError.message),d("Unable to set TDLS state to "+b+".")):(ow.info("TDLS state changed: state = "+b+", status = "+e),c(e))})})};var qw=function(a,b,c,d){d=void 0===d?null:d;Aj.call(this,b);var e=b.yb;this.F=e.sessionId;this.L=e.sg;this.G=a;this.N=d;this.o=fb("mr.mirror.cast.Session");this.D=new Tv;this.u=new yn("mirror.cast.SeqNumGenerator");this.s=new Qv(b.id);this.m=new jw(e,this.G,this.u,this.s,this.N);this.w=null;this.g=new mw(a,e,c,new kw(this.F,this.u,this.s));this.l=!1;this.H=null};q(qw,Aj);h=qw.prototype;
h.start=function(a){var b=this;return Vv(this.D,1,function(c){var d=Cv();return Zea(b).then(function(e){b.l=e;return b.m.start(a,b)}).then(function(){if(b.m.j.F){var e=b.g;e.s.tdlsIsOn=b.l;e.F.start();$ea(b)}else b.g.s.tdlsIsOn=b.l;d.end();b.H=Dv();Xv(c,2);return b})})};
h.stop=function(){var a=this;return Wv(this.D,function(b){a.H&&(a.H.end(),a.H=null);a.g.F.stop();return a.m.stop().then(function(){return a.w?ew(a.w):Promise.resolve()}).then(function(){a.w=null;return a.l?afa(a):Promise.resolve()}).then(function(){a.l=!1;Xv(b,4)})})};
h.co=function(){var a=this,b={sessionId:this.F,seqNum:zn(this.u),type:"PRESENTATION",icons:[],title:yj(this.Dc)};this.o.info("Sending session metadata update to receiver: "+this.F);this.s.sendMessage(b).catch(function(c){a.o.K("Failed to send activity to sink: "+c.message)})};h.Kg=function(a){this.g.Kg(a)};h.xh=function(){return this.g.xh()};h.tf=function(a,b){this.g.tf(a,b);this.o.error(a,b);this.stop()};
var rw=function(a,b){return Yea(a.g,b)},Zea=function(a){a.o.info("maybeEnableTdls_: useTdls = "+a.G.useTdls);return a.G.useTdls?pw(a.L,!0).then(function(b){if("Connected"==b)return a.o.info("Successfully enabled TDLS."),!0;a.o.K("Did not enable TDLS: result="+b);return!1}).catch(function(b){a.o.K("Error while calling enableTDLS()",b);return!1}):Promise.resolve(!1)},afa=function(a){return pw(a.L,!1).catch(function(b){return a.o.error("Error while turning TDLS back off",b)})},$ea=function(a){bfa(a).then(function(b){(b.g||
[]).includes("video")?cfa(a,b):a.o.K(function(){return"Receiver incapable of Media Remoting: "+JSON.stringify(b)})}).catch(function(b){a.o.K("None/Invalid capabilites response. Media Remoting disabled.",b)})},bfa=function(a){return new Promise(function(b,c){var d={type:"GET_CAPABILITIES",sessionId:a.F,seqNum:zn(a.u)};a.o.info(function(){return"Sending GET_CAPABILITIES message: "+JSON.stringify(d)});Sv(a.s,d,"CAPABILITIES_RESPONSE",3E4,function(e,f){if(null==e)return c(f),!0;if("ok"!=e.result||!e.capabilities)return c(Error("Bad response: "+
JSON.stringify(e))),!0;if(e.h!=d.seqNum)return a.o.info(function(){return"Ignoring CAPABILITIES_RESPONSE with different seqNum: "+JSON.stringify(e)}),!1;nb(a.o,function(){return"Received CAPABILITIES_RESPONSE: "+JSON.stringify(e)});b(e.capabilities);return!0})})},cfa=function(a,b){Vv(a.D,2,function(c){var d=a.h.yb.ve||"<UNKNOWN>";if(!d.startsWith("Chromecast")&&!d.startsWith("Eureka Dongle"))return a.o.K('HACK: Media Remoting disabled because the receiver model--"'+(d+'" according to discovery--is not a Chromecast.')),
Xv(c),Promise.resolve();a.w=new dw(a.h,b,a.G,a.u,a.s,a.N);return a.w.initialize(a.W.bind(a),a).catch(function(e){a.o.error("Media Remoting start failed: "+e.message,e)}).then(function(){return Xv(c)})})};qw.prototype.W=function(){var a=this;return Vv(this.D,2,function(b){return new Promise(function(c,d){Wea(a.m).then(function(){Xv(b,3);a.M=!0;rj(a);c(a.X.bind(a))}).catch(function(e){a.tf("Failed to suspend MediaStreamer before starting remoting",e);d(e)})})})};
qw.prototype.X=function(){var a=this;return Vv(this.D,3,function(b){return new Promise(function(c,d){a.m.resume().then(function(){Xv(b,2);a.M=!1;rj(a);c()}).catch(function(e){a.tf("Failed resume MediaStreamer after ending remoting mode",e);d(e)})})})};var sw=function(){pj.call(this,"cast_streaming");this.m=this.D=this.M=this.H=this.l=null;this.mb=this.J="";this.ga=this.u=!1;this.ja=this.ua.bind(this);this.L=this.N=this.W=this.X=this.w=null};q(sw,pj);h=sw.prototype;h.Lg=function(a){this.u=a||!1;this.ga=!0};h.getName=function(){return"cast_streaming"};
h.Xj=function(a,b,c,d,e){var f=this;if(!this.u)return pj.prototype.Xj.call(this,a,b,c,d,e);this.V.info("Start mirroring on route "+a.id);if(!this.ga)return Ai(Error("Not initialized"));var g=new Promise(function(k,m){f.s().then(function(){if(kj(b)&&c.shouldCaptureVideo)return Ti(!1).then(function(p){f.mb=p})}).then(function(){return e?e(a).g:a}).then(function(p){f.J=b;dfa(f,p);var u=f.H.createInterfacePtrAndBind(),A=f.M.createInterfacePtrAndBind(),E=efa(p,c);ffa(f,p,b,d);if(!f.l)throw new Ei("Error to get mirroring service host");
f.D=new mojo.MirroringCastMessageChannelPtr;f.X=Cv();f.l.start(E,u,A,mojo.makeRequest(f.D));f.w=new Aj(a,f.j.lj.bind(f.j));rj(f.w);gfa(f,p,b);f.N=function(){return k(p)};f.L=m}).catch(function(p){f.V.info("Mirroring launch error: "+p);f.og(p.reason);m(p)})});return Bi(g)};h.Lh=function(a,b){return new qw(a,b,20969472,null)};h.rh=function(){Ev(0)};h.oh=function(){Ev(1)};h.pi=function(){Ev(2)};h.ph=function(){Ab("MediaRouter.CastStreaming.Session.End")};
h.og=function(a){Bb("MediaRouter.CastStreaming.Start.Failure",a,Di)};h.qh=function(){Ab("MediaRouter.CastStreaming.Stream.End")};
h.Oi=function(a){var b=this;return this.u?Promise.resolve():(new Promise(function(c){return chrome.metricsPrivate.getIsCrashReportingEnabled(c)})).then(function(c){var d=c&&qea(),e=[9351424];d&&e.push(20969472);return rw(a,e).then(function(f){var g=f[f.length-1];f=tm(f[0].events).catch(function(k){b.V.error("Failed to persist events Blob.",k)});d&&0<g.events.size?Hv(g.events,void 0,b.Ys.bind(b)):c&&Gv("stats.json",g.ug,void 0,void 0);return f})})};h.Ys=function(a){a&&(Kv().g=Date.now())};
h.Wj=function(a){if(this.u)return cb();this.V.info("Received message to upload logs for "+a);return this.g?rw(this.g,[20969472]).then(function(b){b=l(b).next().value;return 0==b.events.size?"":Hv(b.events,a)}):Promise.resolve(hfa(this,a))};
var hfa=function(a,b){var c=window.localStorage.getItem("mr.temp.mirror.cast.Service.eventsBlob");if(null==c||1>c.length)c=null;else{for(var d=new Uint16Array(c.length),e=0;e<c.length;++e)d[e]=c.charCodeAt(e);c=d.buffer;d=(new Uint8Array(c,c.byteLength-1,1))[0];c=new Uint8Array(c,0,c.byteLength-(0==d?2:1));c=new Blob([c],{type:"application/gzip"})}if(null!=c&&0!=c.size)return tm(new Blob),a.V.info("Uploading saved logs for feedback."),Hv(c,b)};h=sw.prototype;
h.onError=function(a){this.L&&(this.L(a),this.N=this.L=null,this.og(9));this.V.info("Mirroring service error: "+a);this.s()};h.didStart=function(){this.N&&(this.N(),this.N=this.L=null);this.X&&(this.X.end(),this.X=null);this.W=Dv();jj(this.J)?this.rh():kj(this.J)?this.oh():mj(this.J)&&this.pi()};h.didStop=function(){this.s()};h.send=function(a){if(this.m){var b=JSON.parse(a.jsonFormatData);nb(this.V,function(){return"Sending message: "+JSON.stringify(b)});this.m.sendMessage(a.jsonFormatData,{namespace:a.messageNamespace})}};
h.Zs=function(a){if(a&&(a.namespace_===mojo.MirroringWebRtcNamespace||a.namespace_===mojo.MirroringRemotingNamespace)&&this.D){var b=new mojo.MirroringCastMessage;b.messageNamespace=a.namespace_;"string"!==typeof a.data?this.V.info("Received non-string as JSON"):(b.jsonFormatData=a.data,this.D.send(b))}};
var dfa=function(a,b){a.H=new mojo.Binding(mojo.MirroringSessionObserver,a,null);a.M=new mojo.Binding(mojo.MirroringCastMessageChannel,a,null);a.m=Vu(b.id);a.m.onMessage=a.Zs.bind(a)},efa=function(a,b){var c=new mojo.MirroringSessionParameters;c.receiverAddress=new mojo.IPAddress;c.receiverAddress.addressBytes=a.yb.sg.split(".").map(function(d){return parseInt(d,10)});c.receiverModelName=a.yb.ve;c.type=b.shouldCaptureVideo&&b.shouldCaptureAudio?mojo.MirroringSessionType.AUDIO_AND_VIDEO:b.shouldCaptureVideo?
mojo.MirroringSessionType.VIDEO_ONLY:mojo.MirroringSessionType.AUDIO_ONLY;return c},ffa=function(a,b,c,d){a.l=new mojo.MirroringServiceHostPtr;b=b.yb.tabId||-1;jj(c)?a.j.getMirroringServiceHostForTab(b,mojo.makeRequest(a.l)):kj(c)?a.j.getMirroringServiceHostForDesktop(-1,a.mb,mojo.makeRequest(a.l)):mj(c)?(b=new mojo.Url,b.url=c,a.j.getMirroringServiceHostForOffscreenTab(b,d||"",mojo.makeRequest(a.l))):a.l=null},gfa=function(a,b,c){jj(c)&&!chrome.tabs.onUpdated.hasListener(a.ja)&&chrome.tabs.onUpdated.addListener(a.ja);
(jj(c)||mj(c))&&uj(a.w,b.yb.tabId)};sw.prototype.ua=function(a,b,c){ij(14);this.w&&vj(this.w,a,b,c)};
sw.prototype.s=function(){chrome.tabs.onUpdated.removeListener(this.ja);return this.u?this.ga?this.l?(this.l.ptr.reset(),this.D=this.l=null,this.m&&this.m.eb(),this.m=null,this.H&&(this.H.close(),this.H=null),this.M&&(this.M.close(),this.M=null),this.j.ji(this.w.h.id),this.w=null,this.mb=this.J="",this.W&&(this.W.end(),this.W=null),this.ph(),Promise.resolve(!0)):Promise.resolve(!1):Promise.reject("Not initialized"):pj.prototype.s.call(this)};
sw.prototype.Yj=function(a,b,c,d,e,f){return this.u?Ai(Error("Mirroring service does not support updating stream")):pj.prototype.Yj.call(this,a,b,c,d,e,f)};sw.prototype.send=sw.prototype.send;sw.prototype.didStop=sw.prototype.didStop;sw.prototype.didStart=sw.prototype.didStart;sw.prototype.onError=sw.prototype.onError;var ifa=new sw;fj("mr.mirror.cast.Service",ifa);
